# Generated by Django 4.0.4 on 2022-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_health', models.SmallIntegerField()),
                ('base_mana', models.SmallIntegerField()),
                ('base_armor', models.SmallIntegerField()),
                ('base_melee_min', models.SmallIntegerField()),
                ('base_melee_max', models.SmallIntegerField()),
                ('base_money_multiplier', models.FloatField(default=1.0)),
                ('base_exp_multiplier', models.FloatField(default=1.0)),
                ('base_rep_multiplier', models.FloatField(default=1.0)),
            ],
        ),
    ]
