# Generated by Django 4.0.4 on 2022-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_health_multiplier', models.FloatField()),
                ('base_mana_multiplier', models.FloatField()),
                ('base_armor_multiplier', models.FloatField()),
                ('base_melee_min_multiplier', models.FloatField()),
                ('base_melee_max_multiplier', models.FloatField()),
                ('base_money_multiplier', models.FloatField()),
                ('base_exp_multiplier', models.FloatField()),
                ('base_rep_multiplier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_health_multiplier', models.FloatField()),
                ('base_mana_multiplier', models.FloatField()),
                ('base_armor_multiplier', models.FloatField()),
                ('base_melee_min_multiplier', models.FloatField()),
                ('base_melee_max_multiplier', models.FloatField()),
                ('base_money_multiplier', models.FloatField()),
                ('base_exp_multiplier', models.FloatField()),
                ('base_rep_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('base_health_multiplier', models.FloatField()),
                ('base_mana_multiplier', models.FloatField()),
                ('base_armor_multiplier', models.FloatField()),
                ('base_melee_min_multiplier', models.FloatField()),
                ('base_melee_max_multiplier', models.FloatField()),
                ('base_money_multiplier', models.FloatField()),
                ('base_exp_multiplier', models.FloatField()),
                ('base_rep_multiplier', models.FloatField(default=1.0)),
            ],
        ),
    ]
