# Generated by Django 4.0.4 on 2022-05-04 23:25

import creatures.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0003_faction_creature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_id', models.IntegerField()),
                ('icon_image', models.ImageField(upload_to=creatures.models.ability_icon_image_path)),
                ('name', models.CharField(max_length=128)),
                ('tooltip', models.TextField()),
                ('cost', models.IntegerField()),
                ('range', models.IntegerField()),
                ('cast_time', models.FloatField()),
                ('gcd', models.FloatField()),
                ('cooldown', models.FloatField()),
                ('value', models.FloatField()),
                ('duration', models.FloatField()),
                ('dispel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispel_types', to='creatures.dispel_type')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilitys', to='creatures.school')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='creatures.ability'),
        ),
    ]
