# Generated by Django 4.0.4 on 2022-05-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0005_rename_dispel_type_dispeltype_alter_ability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='armor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='mana',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='melee_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='melee_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='money',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='reputation',
            field=models.FloatField(default=0.0),
        ),
    ]
