# Generated by Django 4.0.4 on 2022-05-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0006_creature_armor_creature_experience_creature_health_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='base_exp_multiplier',
            new_name='base_experience',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='base_money_multiplier',
            new_name='base_money',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='base_rep_multiplier',
            new_name='base_reputation',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='base_exp_multiplier',
            new_name='base_experience_multiplier',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='base_rep_multiplier',
            new_name='base_reputation_multiplier',
        ),
        migrations.RenameField(
            model_name='expansion',
            old_name='base_exp_multiplier',
            new_name='base_experience_multiplier',
        ),
        migrations.RenameField(
            model_name='expansion',
            old_name='base_rep_multiplier',
            new_name='base_reputation_multiplier',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='base_exp_multiplier',
            new_name='base_experience_multiplier',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='base_rep_multiplier',
            new_name='base_reputation_multiplier',
        ),
        migrations.AddField(
            model_name='creature',
            name='expansion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='creatures.expansion'),
            preserve_default=False,
        ),
    ]
