# Generated by Django 4.0.4 on 2022-05-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0007_rename_base_exp_multiplier_class_base_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='expansion',
        ),
    ]
