# Generated by Django 4.0.4 on 2022-05-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0008_remove_creature_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='expansion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='creatures.expansion'),
        ),
    ]
